### ISSUE TITLE
User signs up to the application by providing their user data

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/puppy.io#1]
As a user, I want to be able to sign up for the application using my email or other forms of authentication. I need to be able to create an account with my email, name, and password specified

**Acceptance Criteria**
- [ ] database table (or equivalent) with the user data is configured 
- [x] if not logged in, the application navigates to the sign up/ login screen
- [x] after clicking on the signup button, the app navigates to sign up a screen where user can provide their name, email, and password
- [ ] after clicking the signup button, the app saves user data in the database (or equivalent)
- [x] README with the tutorial on how to sign up is created

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682270-3ccde101-5426-4d9b-b5b0-2d73cbb2a133.png)

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682304-1b1b2cba-c0d1-4885-b4d7-14cc0dc51f72.png)
