### ISSUE TITLE
Everyone can develop independently thanks to SWAGGER contract

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/puppy.io#12]
As a developer, I want to be able to develop a mobile app and the backend independently. I want to have an OpenAPI contract in a form of SWAGGER created so I can mock the responses on the mobile side and test my backend on the other side

**Acceptance Criteria**
- [x] a SWAGGER contract between mobile and backend created

**Comment by paulinaurbas** [comment]
After after accepting Swagger contract please mock backend endpoints 😄

**Comment by paulinaurbas** [comment]
done :)
