### ISSUE TITLE
User logs into the application

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/puppy.io#2]
As a user, I want to be able to log in to the application

**Acceptance Criteria**
- [x] if not logged in, the application navigates to the sign up/ login screen
- [x] after clicking log in button on the sign up/ login screen, users can log in using their email and password or equivalent
- [x] after logging in, the app navigates to the main screen
- [ ] README with the tutorial on how to log in is created

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682314-aa44a052-d8ad-4170-b5a1-1c63898bb146.png)
