### ISSUE TITLE
Returning user creates a dog offer

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/puppy.io#3]
As a user (returning), I want to be able to create a dog offer, providing its name, breed, age, sex, pictures (max 3), and additional description

**Acceptance Criteria**
- [x] database table (or equivalent) with the dog data is configured 
- [ ] after clicking the add button on the main screen, the app navigates to the add offer screen where the user can fill in the name, breed, age, sex, pictures (max 3), and additional description fields (every field is optional)
- [ ] after submitting the offer it's saved to the database and appears on the main screen
- [ ] README with the tutorial on how to add dog offers is created

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682488-e1f22411-04db-4bc3-a2b4-d272805f2d68.png)
