### ISSUE TITLE
User scrolls through the offers and sees their details

### ISSUE THREAD

**Issue by franpog859** [paulinaurbas/puppy.io#4]
As a user, I want to be able to scroll through the available dog offers 

**Acceptance Criteria**
- [x] on the main screen, the user can scroll through the wall of dog offers
- [ ] after clicking on the offer, its details appear
- [x] README with the tutorial on how to scroll through offers and go to their details is created

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682520-cadf0fda-b3ed-4aac-bc26-a91ae2779a40.png)

**Comment by paulinaurbas** [comment]
![image](https://user-images.githubusercontent.com/32485281/141682537-81535003-3b24-4251-98d9-ca6bc4b23a0f.png)
